version: '3'

services:
  postgres:
    image: postgres:15.2-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      -  postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - .env
    networks:
      - postgres

  api:
    container_name: nestjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres-volume:

