name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Remove Old Files from Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            rm -rf /root/focuson-api

      - name: Transfer Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          source: "."
          target: "/root/focuson-api"
          overwrite: true

  migrations:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Database Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            cd /root/focuson-api
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm run migrate:run

  deploy:
    needs: migrations
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_PASSPHRASE }}
          script: |
            cd /root/focuson-api
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm ci --only=production
            pm2 restart focuson-api || pm2 start ecosystem.config.js --env production
